### ISSUE TITLE
Desmembramento

### ISSUE THREAD

**Issue by mrph** [mrph/-lan-station#1]
Objetos/armas com mais de uma flag além de SHARP não estão cortando membros.

A cabeça não pode ser desmembrada.

**Comment by wat141** [comment]
A cabeça agora pode ser desmembrada.

**Comment by wat141** [comment]
Pode dar um exemplo da questão do SHARP? Em que item tentou usar e que não deu certo?

**Comment by mrph** [comment]
Nenhum item além de uma katana tinha a flag sharp, por isso não funcionava.
